"""empty message

Revision ID: 63e05f6973
Revises: None
Create Date: 2015-10-20 22:14:30.726479

"""

# revision identifiers, used by Alembic.
revision = '63e05f6973'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('saying', sa.String(length=34), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'saying')
    ### end Alembic commands ###
