"""empty message

Revision ID: 3a245e7724f
Revises: None
Create Date: 2015-11-23 11:33:41.475702

"""

# revision identifiers, used by Alembic.
revision = '3a245e7724f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('user_birthday', sa.DateTime(), nullable=True))
    op.add_column('user_table', sa.Column('user_nickname', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'user_nickname')
    op.drop_column('user_table', 'user_birthday')
    ### end Alembic commands ###
